# Latin ones are the SUBJECT of this module, not a typo in it.
"""The golden set: 77 real Uzbek and Russian given names, both scripts, frozen.

Every row was produced by the resolver and then read by a human before it was frozen. This
is a REGRESSION fence, not a specification: when a row changes, someone has to look at the
new value and agree with it before the diff lands. That is the point — the name subsystem is
where a silent "improvement" costs a customer a mispronounced name.

Coverage is deliberate, not a sample: Uzbek Latin typed with U+2018, U+0027, U+0060 and
U+2019 for the mark; the ``oʻ``/``gʻ`` digraphs; the tutuq belgisi (``Maʼruf``, ``Raʼno``);
Uzbek Cyrillic with Ў Қ Ғ Ҳ; Russian Cyrillic with ё (``Алёна``, ``Пётр``, ``Артём``), ь, ъ
and й; and Russian names typed in Latin by a user whose keyboard has no Cyrillic.

``ui_language`` is on every row because the interface language and the output language are
chosen independently: it only ever acts as a tiebreaker for a name whose script cannot
settle the question on its own.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final

from hbd.contracts import Language, NameStrategy, Script

__all__ = ["GoldenName", "GOLDEN_NAMES"]

# Local aliases keep one expectation on one screen line. Nothing else uses them.
UZL: Final = Language.UZ_LATN
UZC: Final = Language.UZ_CYRL
RU: Final = Language.RU
EN: Final = Language.EN
LATIN: Final = Script.LATIN
CYRILLIC: Final = Script.CYRILLIC
CANONICAL: Final = NameStrategy.CANONICAL
STRIPPED: Final = NameStrategy.STRIPPED
ASCII: Final = NameStrategy.ASCII
CYRILLIC_FORM: Final = NameStrategy.CYRILLIC
HYPHENATED: Final = NameStrategy.HYPHENATED
PHONETIC: Final = NameStrategy.PHONETIC


@dataclass(frozen=True, slots=True)
class GoldenName:
    """One frozen expectation: what ``resolve_name`` must return for ``typed``."""

    typed: str
    ui_language: Language
    display: str
    script: Script
    language: Language
    lookup_key: str
    candidates: tuple[tuple[NameStrategy, str], ...]


#: Ordered Uzbek Latin, Uzbek Cyrillic, Russian Cyrillic, then Russian-in-Latin.
GOLDEN_NAMES: Final[tuple[GoldenName, ...]] = (
    GoldenName(
        typed="G‘ulomjon",
        ui_language=UZL,
        display="Gʻulomjon",
        script=LATIN,
        language=UZL,
        lookup_key="gulomjon",
        candidates=(
            (STRIPPED, "Gulomjon"),
            (CANONICAL, "Gʻulomjon"),
            (HYPHENATED, "Gu-lom-jon"),
            (ASCII, "G'ulomjon"),
            (PHONETIC, "Ghoolomjon"),
        ),
    ),
    GoldenName(
        typed="O`ktam",
        ui_language=UZL,
        display="Oʻktam",
        script=LATIN,
        language=UZL,
        lookup_key="oktam",
        candidates=(
            (STRIPPED, "Oktam"),
            (CANONICAL, "Oʻktam"),
            (HYPHENATED, "Ok-tam"),
            (ASCII, "O'ktam"),
        ),
    ),
    GoldenName(
        typed="Bekzod",
        ui_language=UZL,
        display="Bekzod",
        script=LATIN,
        language=UZL,
        lookup_key="bekzod",
        candidates=((STRIPPED, "Bekzod"), (HYPHENATED, "Bek-zod")),
    ),
    GoldenName(
        typed="Nigora",
        ui_language=UZL,
        display="Nigora",
        script=LATIN,
        language=UZL,
        lookup_key="nigora",
        candidates=((STRIPPED, "Nigora"), (HYPHENATED, "Ni-go-ra"), (PHONETIC, "Neegora")),
    ),
    GoldenName(
        typed="Dilnoza",
        ui_language=UZL,
        display="Dilnoza",
        script=LATIN,
        language=UZL,
        lookup_key="dilnoza",
        candidates=((STRIPPED, "Dilnoza"), (HYPHENATED, "Dil-no-za"), (PHONETIC, "Deelnoza")),
    ),
    GoldenName(
        typed="Shohruh",
        ui_language=UZL,
        display="Shohruh",
        script=LATIN,
        language=UZL,
        lookup_key="shohruh",
        candidates=((STRIPPED, "Shohruh"), (HYPHENATED, "Shoh-ruh"), (PHONETIC, "Shohrooh")),
    ),
    GoldenName(
        typed="Xurshid",
        ui_language=UZL,
        display="Xurshid",
        script=LATIN,
        language=UZL,
        lookup_key="hurshid",
        candidates=((STRIPPED, "Xurshid"), (HYPHENATED, "Xur-shid"), (PHONETIC, "Khoorsheed")),
    ),
    GoldenName(
        typed="Aziza",
        ui_language=UZL,
        display="Aziza",
        script=LATIN,
        language=UZL,
        lookup_key="aziza",
        candidates=((STRIPPED, "Aziza"), (HYPHENATED, "A-zi-za"), (PHONETIC, "Azeeza")),
    ),
    GoldenName(
        typed="Jasur",
        ui_language=UZL,
        display="Jasur",
        script=LATIN,
        language=UZL,
        lookup_key="jasur",
        candidates=((STRIPPED, "Jasur"), (HYPHENATED, "Ja-sur"), (PHONETIC, "Jasoor")),
    ),
    GoldenName(
        typed="Malika",
        ui_language=UZL,
        display="Malika",
        script=LATIN,
        language=UZL,
        lookup_key="malika",
        candidates=((STRIPPED, "Malika"), (HYPHENATED, "Ma-li-ka"), (PHONETIC, "Maleeka")),
    ),
    GoldenName(
        typed="Sardor",
        ui_language=UZL,
        display="Sardor",
        script=LATIN,
        language=UZL,
        lookup_key="sardor",
        candidates=((STRIPPED, "Sardor"), (HYPHENATED, "Sar-dor")),
    ),
    GoldenName(
        typed="Nodira",
        ui_language=UZL,
        display="Nodira",
        script=LATIN,
        language=UZL,
        lookup_key="nodira",
        candidates=((STRIPPED, "Nodira"), (HYPHENATED, "No-di-ra"), (PHONETIC, "Nodeera")),
    ),
    GoldenName(
        typed="Ulug'bek",
        ui_language=UZL,
        display="Ulugʻbek",
        script=LATIN,
        language=UZL,
        lookup_key="ulugbek",
        candidates=(
            (STRIPPED, "Ulugbek"),
            (CANONICAL, "Ulugʻbek"),
            (HYPHENATED, "U-lug-bek"),
            (ASCII, "Ulug'bek"),
            (PHONETIC, "Oolooghbek"),
        ),
    ),
    GoldenName(
        typed="Zilola",
        ui_language=UZL,
        display="Zilola",
        script=LATIN,
        language=UZL,
        lookup_key="zilola",
        candidates=((STRIPPED, "Zilola"), (HYPHENATED, "Zi-lo-la"), (PHONETIC, "Zeelola")),
    ),
    GoldenName(
        typed="Feruza",
        ui_language=UZL,
        display="Feruza",
        script=LATIN,
        language=UZL,
        lookup_key="feruza",
        candidates=((STRIPPED, "Feruza"), (HYPHENATED, "Fe-ru-za"), (PHONETIC, "Ferooza")),
    ),
    GoldenName(
        typed="Otabek",
        ui_language=UZL,
        display="Otabek",
        script=LATIN,
        language=UZL,
        lookup_key="otabek",
        candidates=((STRIPPED, "Otabek"), (HYPHENATED, "O-ta-bek")),
    ),
    GoldenName(
        typed="Mohira",
        ui_language=UZL,
        display="Mohira",
        script=LATIN,
        language=UZL,
        lookup_key="mohira",
        candidates=((STRIPPED, "Mohira"), (HYPHENATED, "Mo-hi-ra"), (PHONETIC, "Moheera")),
    ),
    GoldenName(
        typed="Rustam",
        ui_language=UZL,
        display="Rustam",
        script=LATIN,
        language=UZL,
        lookup_key="rustam",
        candidates=((STRIPPED, "Rustam"), (HYPHENATED, "Rus-tam"), (PHONETIC, "Roostam")),
    ),
    GoldenName(
        typed="Sevara",
        ui_language=UZL,
        display="Sevara",
        script=LATIN,
        language=UZL,
        lookup_key="sevara",
        candidates=((STRIPPED, "Sevara"), (HYPHENATED, "Se-va-ra")),
    ),
    GoldenName(
        typed="Alisher",
        ui_language=UZL,
        display="Alisher",
        script=LATIN,
        language=UZL,
        lookup_key="alisher",
        candidates=((STRIPPED, "Alisher"), (HYPHENATED, "A-li-sher"), (PHONETIC, "Aleesher")),
    ),
    GoldenName(
        typed="Ma'ruf",
        ui_language=UZL,
        display="Maʼruf",
        script=LATIN,
        language=UZL,
        lookup_key="maruf",
        candidates=(
            (STRIPPED, "Maruf"),
            (CANONICAL, "Maʼruf"),
            (HYPHENATED, "Ma-ruf"),
            (ASCII, "Ma'ruf"),
            (PHONETIC, "Maroof"),
        ),
    ),
    GoldenName(
        typed="Ra’no",
        ui_language=UZL,
        display="Raʼno",
        script=LATIN,
        language=UZL,
        lookup_key="rano",
        candidates=(
            (STRIPPED, "Rano"),
            (CANONICAL, "Raʼno"),
            (HYPHENATED, "Ra-no"),
            (ASCII, "Ra'no"),
        ),
    ),
    GoldenName(
        typed="Sanjar",
        ui_language=UZL,
        display="Sanjar",
        script=LATIN,
        language=UZL,
        lookup_key="sanjar",
        candidates=((STRIPPED, "Sanjar"), (HYPHENATED, "San-jar")),
    ),
    GoldenName(
        typed="Gulnora",
        ui_language=UZL,
        display="Gulnora",
        script=LATIN,
        language=UZL,
        lookup_key="gulnora",
        candidates=((STRIPPED, "Gulnora"), (HYPHENATED, "Gul-no-ra"), (PHONETIC, "Goolnora")),
    ),
    GoldenName(
        typed="Yulduz",
        ui_language=UZL,
        display="Yulduz",
        script=LATIN,
        language=UZL,
        lookup_key="iulduz",
        candidates=((STRIPPED, "Yulduz"), (HYPHENATED, "Yul-duz"), (PHONETIC, "Yooldooz")),
    ),
    GoldenName(
        typed="Elyor",
        ui_language=UZL,
        display="Elyor",
        script=LATIN,
        language=UZL,
        lookup_key="elior",
        candidates=((STRIPPED, "Elyor"), (HYPHENATED, "El-yor")),
    ),
    GoldenName(
        typed="Ziyoda",
        ui_language=UZL,
        display="Ziyoda",
        script=LATIN,
        language=UZL,
        lookup_key="zioda",
        candidates=((STRIPPED, "Ziyoda"), (HYPHENATED, "Zi-yo-da"), (PHONETIC, "Zeeyoda")),
    ),
    GoldenName(
        typed="Qodir",
        ui_language=UZL,
        display="Qodir",
        script=LATIN,
        language=UZL,
        lookup_key="kodir",
        candidates=((STRIPPED, "Qodir"), (HYPHENATED, "Qo-dir"), (PHONETIC, "Kodeer")),
    ),
    GoldenName(
        typed="To‘lqin",
        ui_language=UZL,
        display="Toʻlqin",
        script=LATIN,
        language=UZL,
        lookup_key="tolkin",
        candidates=(
            (STRIPPED, "Tolqin"),
            (CANONICAL, "Toʻlqin"),
            (HYPHENATED, "Tol-qin"),
            (ASCII, "To'lqin"),
            (PHONETIC, "Tolkeen"),
        ),
    ),
    GoldenName(
        typed="Shahzod",
        ui_language=UZL,
        display="Shahzod",
        script=LATIN,
        language=UZL,
        lookup_key="shahzod",
        candidates=((STRIPPED, "Shahzod"), (HYPHENATED, "Shah-zod")),
    ),
    GoldenName(
        typed="Muhammad",
        ui_language=UZL,
        display="Muhammad",
        script=LATIN,
        language=UZL,
        lookup_key="muhamad",
        candidates=((STRIPPED, "Muhammad"), (HYPHENATED, "Mu-ham-mad"), (PHONETIC, "Moohammad")),
    ),
    GoldenName(
        typed="Zebo",
        ui_language=UZL,
        display="Zebo",
        script=LATIN,
        language=UZL,
        lookup_key="zebo",
        candidates=((STRIPPED, "Zebo"), (HYPHENATED, "Ze-bo")),
    ),
    GoldenName(
        typed="Iskandar",
        ui_language=UZL,
        display="Iskandar",
        script=LATIN,
        language=UZL,
        lookup_key="iskandar",
        candidates=((STRIPPED, "Iskandar"), (HYPHENATED, "Is-kan-dar"), (PHONETIC, "Eeskandar")),
    ),
    GoldenName(
        typed="Laziz",
        ui_language=UZL,
        display="Laziz",
        script=LATIN,
        language=UZL,
        lookup_key="laziz",
        candidates=((STRIPPED, "Laziz"), (HYPHENATED, "La-ziz"), (PHONETIC, "Lazeez")),
    ),
    GoldenName(
        typed="Oygul",
        ui_language=UZL,
        display="Oygul",
        script=LATIN,
        language=UZL,
        lookup_key="oigul",
        candidates=((STRIPPED, "Oygul"), (HYPHENATED, "Oy-gul"), (PHONETIC, "Oygool")),
    ),
    GoldenName(
        typed="Umida",
        ui_language=UZL,
        display="Umida",
        script=LATIN,
        language=UZL,
        lookup_key="umida",
        candidates=((STRIPPED, "Umida"), (HYPHENATED, "U-mi-da"), (PHONETIC, "Oomeeda")),
    ),
    GoldenName(
        typed="Farrux",
        ui_language=UZL,
        display="Farrux",
        script=LATIN,
        language=UZL,
        lookup_key="faruh",
        candidates=((STRIPPED, "Farrux"), (HYPHENATED, "Far-rux"), (PHONETIC, "Farrookh")),
    ),
    GoldenName(
        typed="Nafisa",
        ui_language=UZL,
        display="Nafisa",
        script=LATIN,
        language=UZL,
        lookup_key="nafisa",
        candidates=((STRIPPED, "Nafisa"), (HYPHENATED, "Na-fi-sa"), (PHONETIC, "Nafeesa")),
    ),
    GoldenName(
        typed="Doniyor",
        ui_language=UZL,
        display="Doniyor",
        script=LATIN,
        language=UZL,
        lookup_key="donior",
        candidates=((STRIPPED, "Doniyor"), (HYPHENATED, "Do-ni-yor"), (PHONETIC, "Doneeyor")),
    ),
    GoldenName(
        typed="Kamola",
        ui_language=UZL,
        display="Kamola",
        script=LATIN,
        language=UZL,
        lookup_key="kamola",
        candidates=((STRIPPED, "Kamola"), (HYPHENATED, "Ka-mo-la")),
    ),
    GoldenName(
        typed="Ғуломжон",
        ui_language=UZC,
        display="Ғуломжон",
        script=CYRILLIC,
        language=UZC,
        lookup_key="gulomjon",
        candidates=(
            (STRIPPED, "Ғуломжон"),
            (HYPHENATED, "Ғу-лом-жон"),
            (ASCII, "G'ulomjon"),
            (PHONETIC, "Ghoolomjon"),
        ),
    ),
    GoldenName(
        typed="Ўктам",
        ui_language=UZC,
        display="Ўктам",
        script=CYRILLIC,
        language=UZC,
        lookup_key="oktam",
        candidates=(
            (STRIPPED, "Ўктам"),
            (HYPHENATED, "Ўк-там"),
            (ASCII, "O'ktam"),
            (PHONETIC, "Oktam"),
        ),
    ),
    GoldenName(
        typed="Нигора",
        ui_language=UZC,
        display="Нигора",
        script=CYRILLIC,
        language=UZC,
        lookup_key="nigora",
        candidates=(
            (STRIPPED, "Нигора"),
            (HYPHENATED, "Ни-го-ра"),
            (ASCII, "Nigora"),
            (PHONETIC, "Neegora"),
        ),
    ),
    GoldenName(
        typed="Шоҳруҳ",
        ui_language=UZC,
        display="Шоҳруҳ",
        script=CYRILLIC,
        language=UZC,
        lookup_key="shohruh",
        candidates=(
            (STRIPPED, "Шоҳруҳ"),
            (HYPHENATED, "Шоҳ-руҳ"),
            (ASCII, "Shohruh"),
            (PHONETIC, "Shohrooh"),
        ),
    ),
    GoldenName(
        typed="Хуршид",
        ui_language=UZC,
        display="Хуршид",
        script=CYRILLIC,
        language=UZC,
        lookup_key="hurshid",
        candidates=(
            (STRIPPED, "Хуршид"),
            (HYPHENATED, "Хур-шид"),
            (ASCII, "Xurshid"),
            (PHONETIC, "Khoorsheed"),
        ),
    ),
    GoldenName(
        typed="Улуғбек",
        ui_language=UZC,
        display="Улуғбек",
        script=CYRILLIC,
        language=UZC,
        lookup_key="ulugbek",
        candidates=(
            (STRIPPED, "Улуғбек"),
            (HYPHENATED, "У-луғ-бек"),
            (ASCII, "Ulug'bek"),
            (PHONETIC, "Oolooghbek"),
        ),
    ),
    GoldenName(
        typed="Азиза",
        ui_language=UZC,
        display="Азиза",
        script=CYRILLIC,
        language=UZC,
        lookup_key="aziza",
        candidates=(
            (STRIPPED, "Азиза"),
            (HYPHENATED, "А-зи-за"),
            (ASCII, "Aziza"),
            (PHONETIC, "Azeeza"),
        ),
    ),
    GoldenName(
        typed="Дилноза",
        ui_language=UZC,
        display="Дилноза",
        script=CYRILLIC,
        language=UZC,
        lookup_key="dilnoza",
        candidates=(
            (STRIPPED, "Дилноза"),
            (HYPHENATED, "Дил-но-за"),
            (ASCII, "Dilnoza"),
            (PHONETIC, "Deelnoza"),
        ),
    ),
    GoldenName(
        typed="Отабек",
        ui_language=UZC,
        display="Отабек",
        script=CYRILLIC,
        language=UZC,
        lookup_key="otabek",
        candidates=((STRIPPED, "Отабек"), (HYPHENATED, "О-та-бек"), (ASCII, "Otabek")),
    ),
    GoldenName(
        typed="Санъат",
        ui_language=UZC,
        display="Санъат",
        script=CYRILLIC,
        language=UZC,
        lookup_key="sanat",
        candidates=(
            (STRIPPED, "Санъат"),
            (HYPHENATED, "Санъ-ат"),
            (ASCII, "San'at"),
            (PHONETIC, "Sanat"),
        ),
    ),
    GoldenName(
        typed="Мохира",
        ui_language=UZC,
        display="Мохира",
        script=CYRILLIC,
        language=UZC,
        lookup_key="mohira",
        candidates=(
            (STRIPPED, "Мохира"),
            (HYPHENATED, "Мо-хи-ра"),
            (ASCII, "Moxira"),
            (PHONETIC, "Mokheera"),
        ),
    ),
    GoldenName(
        typed="Жасур",
        ui_language=UZC,
        display="Жасур",
        script=CYRILLIC,
        language=UZC,
        lookup_key="jasur",
        candidates=(
            (STRIPPED, "Жасур"),
            (HYPHENATED, "Жа-сур"),
            (ASCII, "Jasur"),
            (PHONETIC, "Jasoor"),
        ),
    ),
    GoldenName(
        typed="Алёна",
        ui_language=RU,
        display="Алёна",
        script=CYRILLIC,
        language=RU,
        lookup_key="alena",
        candidates=((STRIPPED, "Алёна"), (HYPHENATED, "А-лё-на"), (ASCII, "Alyona")),
    ),
    GoldenName(
        typed="Елена",
        ui_language=RU,
        display="Елена",
        script=CYRILLIC,
        language=RU,
        lookup_key="ielena",
        candidates=((STRIPPED, "Елена"), (HYPHENATED, "Е-ле-на"), (ASCII, "Yelena")),
    ),
    GoldenName(
        typed="Владимир",
        ui_language=RU,
        display="Владимир",
        script=CYRILLIC,
        language=RU,
        lookup_key="vladimir",
        candidates=(
            (STRIPPED, "Владимир"),
            (HYPHENATED, "Вла-ди-мир"),
            (ASCII, "Vladimir"),
            (PHONETIC, "Vladeemeer"),
        ),
    ),
    GoldenName(
        typed="Дмитрий",
        ui_language=RU,
        display="Дмитрий",
        script=CYRILLIC,
        language=RU,
        lookup_key="dmitri",
        candidates=(
            (STRIPPED, "Дмитрий"),
            (HYPHENATED, "Дмит-рий"),
            (ASCII, "Dmitriy"),
            (PHONETIC, "Dmeetreey"),
        ),
    ),
    GoldenName(
        typed="Наталья",
        ui_language=RU,
        display="Наталья",
        script=CYRILLIC,
        language=RU,
        lookup_key="natalia",
        candidates=((STRIPPED, "Наталья"), (HYPHENATED, "На-таль-я"), (ASCII, "Natalya")),
    ),
    GoldenName(
        typed="Сергей",
        ui_language=RU,
        display="Сергей",
        script=CYRILLIC,
        language=RU,
        lookup_key="sergei",
        candidates=((STRIPPED, "Сергей"), (HYPHENATED, "Сер-гей"), (ASCII, "Sergey")),
    ),
    GoldenName(
        typed="Ольга",
        ui_language=RU,
        display="Ольга",
        script=CYRILLIC,
        language=RU,
        lookup_key="olga",
        candidates=((STRIPPED, "Ольга"), (HYPHENATED, "Оль-га"), (ASCII, "Olga")),
    ),
    GoldenName(
        typed="Екатерина",
        ui_language=RU,
        display="Екатерина",
        script=CYRILLIC,
        language=RU,
        lookup_key="iekaterina",
        candidates=(
            (STRIPPED, "Екатерина"),
            (HYPHENATED, "Е-ка-те-ри-на"),
            (ASCII, "Yekaterina"),
            (PHONETIC, "Yekatereena"),
        ),
    ),
    GoldenName(
        typed="Юлия",
        ui_language=RU,
        display="Юлия",
        script=CYRILLIC,
        language=RU,
        lookup_key="iulia",
        candidates=(
            (STRIPPED, "Юлия"),
            (HYPHENATED, "Ю-ли-я"),
            (ASCII, "Yuliya"),
            (PHONETIC, "Yooleeya"),
        ),
    ),
    GoldenName(
        typed="Михаил",
        ui_language=RU,
        display="Михаил",
        script=CYRILLIC,
        language=RU,
        lookup_key="mihail",
        candidates=(
            (STRIPPED, "Михаил"),
            (HYPHENATED, "Ми-ха-ил"),
            (ASCII, "Mikhail"),
            (PHONETIC, "Meekhaeel"),
        ),
    ),
    GoldenName(
        typed="Анастасия",
        ui_language=RU,
        display="Анастасия",
        script=CYRILLIC,
        language=RU,
        lookup_key="anastasia",
        candidates=(
            (STRIPPED, "Анастасия"),
            (HYPHENATED, "А-нас-та-си-я"),
            (ASCII, "Anastasiya"),
            (PHONETIC, "Anastaseeya"),
        ),
    ),
    GoldenName(
        typed="Пётр",
        ui_language=RU,
        display="Пётр",
        script=CYRILLIC,
        language=RU,
        lookup_key="petr",
        candidates=((STRIPPED, "Пётр"), (ASCII, "Pyotr")),
    ),
    GoldenName(
        typed="Жанна",
        ui_language=RU,
        display="Жанна",
        script=CYRILLIC,
        language=RU,
        lookup_key="jana",
        candidates=((STRIPPED, "Жанна"), (HYPHENATED, "Жан-на"), (ASCII, "Zhanna")),
    ),
    GoldenName(
        typed="Ирина",
        ui_language=RU,
        display="Ирина",
        script=CYRILLIC,
        language=RU,
        lookup_key="irina",
        candidates=(
            (STRIPPED, "Ирина"),
            (HYPHENATED, "И-ри-на"),
            (ASCII, "Irina"),
            (PHONETIC, "Eereena"),
        ),
    ),
    GoldenName(
        typed="Артём",
        ui_language=RU,
        display="Артём",
        script=CYRILLIC,
        language=RU,
        lookup_key="artem",
        candidates=((STRIPPED, "Артём"), (HYPHENATED, "Ар-тём"), (ASCII, "Artyom")),
    ),
    GoldenName(
        typed="Ксения",
        ui_language=RU,
        display="Ксения",
        script=CYRILLIC,
        language=RU,
        lookup_key="ksenia",
        candidates=(
            (STRIPPED, "Ксения"),
            (HYPHENATED, "Ксе-ни-я"),
            (ASCII, "Kseniya"),
            (PHONETIC, "Kseneeya"),
        ),
    ),
    GoldenName(
        typed="Николай",
        ui_language=RU,
        display="Николай",
        script=CYRILLIC,
        language=RU,
        lookup_key="nikolai",
        candidates=(
            (STRIPPED, "Николай"),
            (HYPHENATED, "Ни-ко-лай"),
            (ASCII, "Nikolay"),
            (PHONETIC, "Neekolay"),
        ),
    ),
    GoldenName(
        typed="Татьяна",
        ui_language=RU,
        display="Татьяна",
        script=CYRILLIC,
        language=RU,
        lookup_key="tatiana",
        candidates=((STRIPPED, "Татьяна"), (HYPHENATED, "Тать-я-на"), (ASCII, "Tatyana")),
    ),
    GoldenName(
        typed="Евгений",
        ui_language=RU,
        display="Евгений",
        script=CYRILLIC,
        language=RU,
        lookup_key="ievgeni",
        candidates=(
            (STRIPPED, "Евгений"),
            (HYPHENATED, "Ев-ге-ний"),
            (ASCII, "Yevgeniy"),
            (PHONETIC, "Yevgeneey"),
        ),
    ),
    GoldenName(
        typed="Светлана",
        ui_language=RU,
        display="Светлана",
        script=CYRILLIC,
        language=RU,
        lookup_key="svetlana",
        candidates=((STRIPPED, "Светлана"), (HYPHENATED, "Свет-ла-на"), (ASCII, "Svetlana")),
    ),
    GoldenName(
        typed="Alyona",
        ui_language=RU,
        display="Alyona",
        script=LATIN,
        language=UZL,
        lookup_key="aliona",
        candidates=((STRIPPED, "Alyona"), (HYPHENATED, "Al-yo-na")),
    ),
    GoldenName(
        typed="Mikhail",
        ui_language=EN,
        display="Mikhail",
        script=LATIN,
        language=EN,
        lookup_key="mihail",
        candidates=((STRIPPED, "Mikhail"), (HYPHENATED, "Mik-ha-il"), (PHONETIC, "Meekhaeel")),
    ),
    GoldenName(
        typed="Zhanna",
        ui_language=RU,
        display="Zhanna",
        script=LATIN,
        language=UZL,
        lookup_key="jana",
        candidates=((STRIPPED, "Zhanna"), (HYPHENATED, "Zhan-na")),
    ),
    GoldenName(
        typed="Ekaterina",
        ui_language=EN,
        display="Ekaterina",
        script=LATIN,
        language=EN,
        lookup_key="ekaterina",
        candidates=(
            (STRIPPED, "Ekaterina"),
            (HYPHENATED, "E-ka-te-ri-na"),
            (PHONETIC, "Ekatereena"),
        ),
    ),
    GoldenName(
        typed="Anastasiya",
        ui_language=EN,
        display="Anastasiya",
        script=LATIN,
        language=EN,
        lookup_key="anastasia",
        candidates=(
            (STRIPPED, "Anastasiya"),
            (HYPHENATED, "A-nas-ta-si-ya"),
            (PHONETIC, "Anastaseeya"),
        ),
    ),
)
