"""The ``vendor_balances`` WRITER, and the trailing measurement behind "songs remaining".

Beside :mod:`bayram.db.vendor_usage` rather than under ``bayram.db.admin``, and the placement is
structural rather than tidy. ``bayram.db.admin`` is the admin panel's persistence and nothing
there commits, because the caller owns the transaction. This module is neither: it runs in
the ARQ worker and owns its transaction outright, exactly like ``DbUsageSink``, whose
reasoning applies verbatim — joining whatever transaction the caller happens to be in would
let an unrelated rollback erase the record of a probe that really happened. Keeping it out
of ``bayram.db.admin`` is also the second, structural expression of the security boundary: the
admin package holds no module that can WRITE this table, and no module that can reach a
vendor.

**THE COLUMN-SELECTIVE FAILURE UPSERT IS THE POINT OF THIS MODULE.** There are two
statements, not one, because the failure path must name a STRICT SUBSET of the columns —
everything it does NOT name is what survives a vendor outage. One statement passing ``None``
for the unmeasured quantities would blank the last known balance on the first 500, which is
the exact opposite of what the tile is for: an operator wants the last known figure most at
the moment the vendor is down. The set-difference between the two update mappings IS the
design, so both are spelled out by hand and neither is generated by filtering a dict, where
a later refactor could quietly widen one.

``consecutive_failures`` increments as a COLUMN EXPRESSION inside the ``DO UPDATE`` clause,
which both dialects support, so two workers racing the same window cannot lose a count to a
read-modify-write.

**IT NEVER RAISES**, for ``DbUsageSink``'s stated reason: instrumentation that stops working
looks exactly like a deployment with no traffic. A failed write is logged with the vendor
and the error, and the caller continues to the next probe.

**THE DIVISOR IS MEASURED, NOT CONFIGURED, and that is a correction worth recording.**
``music_usd_per_minute`` and ``elevenlabs_usd_per_character`` are NOT a per-song rate; they
are one layer upstream — the rates that make ``vendor_usage.cost_usd`` non-``NULL`` at all.
Turning them into a per-song figure would need an assumed song shape (how many characters is
a greeting, how many tokens is a lyric, how many seconds is a render), none of which is a
setting and all of which would be invented — fabricating precisely the number
``vendor_balances`` exists not to fabricate. :func:`measure_per_song_rate` divides what was
actually spent by the orders it was actually spent on, and returns ``None`` rather than a
zero whenever it cannot. The consequence is honest and visible: with the shipped rate card
(all four ``BAYRAM_LLM_*_USD_PER_MILLION_*`` at 0.0) every OpenRouter ``cost_usd`` is ``NULL``,
the divisor is ``None``, all three estimate columns stay ``NULL`` together under
``ck_vendor_balances_estimate_carries_its_basis``, and the tile reads "needs balances".
"""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import TYPE_CHECKING, Any, Final

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker
from sqlalchemy.orm import InstrumentedAttribute

from bayram.contracts import BalanceEstimateBasis, OrderState, Vendor
from bayram.db.credit_sql import upsert_statement
from bayram.db.models.order import OrderRow
from bayram.db.models.vendor_balance import (
    ERROR_CODE_LENGTH,
    PLAN_TIER_LENGTH,
    PROBE_NAME_LENGTH,
    RESET_HINT_LENGTH,
    STATUS_LENGTH,
    VendorBalanceRow,
)
from bayram.db.models.vendor_usage import VendorUsageRow
from bayram.logging import get_logger

if TYPE_CHECKING:  # pragma: no cover - a typing-only edge, see the note below
    # Imported for the annotation and NOT at runtime, on purpose. ``bayram.db`` is the lower
    # layer and ``bayram.runtime`` is the higher one; a runtime import here would invert that
    # for the sake of a type name. The writer only ever reads attributes off the probe, so
    # the annotation is all it needs.
    from bayram.runtime.vendor_balance_probes import BalanceProbe

__all__ = ["record_probe", "measure_per_song_rate", "PerSongRate"]

_LOG = get_logger(__name__)

#: The two columns the primary key is made of, and therefore the ``ON CONFLICT`` target.
#: One row per billing account, so a duplicate is impossible rather than merely unusual.
_CONFLICT_TARGET: Final[tuple[str, ...]] = ("vendor", "is_fallback")

#: ``(rate, basis)``. The two always travel together, because a divisor whose provenance is
#: unknown cannot be trusted differently from one whose provenance is known — which is the
#: whole argument for :class:`bayram.contracts.BalanceEstimateBasis`.
type PerSongRate = tuple[float, BalanceEstimateBasis]


def _fit(value: str | None, limit: int) -> str | None:
    """Trim a vendor's own word to the column that holds it.

    Done HERE and not in the probe because this is the layer allowed to import the model
    that owns those widths. A vendor is free to lengthen its tier vocabulary, and a
    ``StringDataRightTruncation`` on Postgres would lose a whole probe over a cosmetic
    field.
    """
    return value[:limit] if value is not None else None


def _songs_remaining(balance_remaining: float | None, rate: float) -> int | None:
    """FLOOR, never round.

    A rounded-up "1 song remaining" on a balance that cannot pay for one is precisely the
    failure this tile exists to prevent, and ``//`` on a positive divisor is the whole
    guard.
    """
    if balance_remaining is None or rate <= 0.0:
        return None
    return int(balance_remaining // rate)


def _measured_values(
    probe: BalanceProbe, divisor: PerSongRate | None, at: datetime
) -> dict[str, Any]:
    """Everything a SUCCESSFUL probe writes, quantities included."""
    reading = probe.reading
    assert reading is not None, "a successful probe carries a reading by construction"
    rate = divisor[0] if divisor is not None else None
    songs = _songs_remaining(reading.balance_remaining, rate) if rate is not None else None
    # All three estimate columns move together or none of them do — the database refuses any
    # other combination, and building them in one place is what keeps that a fact rather
    # than a promise three call sites keep.
    has_estimate = songs is not None and rate is not None and divisor is not None
    return {
        "balance_remaining": reading.balance_remaining,
        "balance_total": reading.balance_total,
        "balance_used": reading.balance_used,
        "is_unbounded": reading.is_unbounded,
        "quota_resets_at": reading.quota_resets_at,
        "quota_reset_hint": _fit(reading.quota_reset_hint, RESET_HINT_LENGTH),
        "plan_tier": _fit(reading.plan_tier, PLAN_TIER_LENGTH),
        "subscription_status": _fit(reading.subscription_status, STATUS_LENGTH),
        "songs_remaining": songs if has_estimate else None,
        "per_song_rate": rate if has_estimate else None,
        "estimate_basis": divisor[1] if has_estimate and divisor is not None else None,
        "fetched_at": at,
        "checked_at": at,
        "is_last_poll_ok": True,
        "http_status": probe.http_status,
        "error_code": None,
        "consecutive_failures": 0,
        "updated_at": at,
    }


def _identity(probe: BalanceProbe, at: datetime) -> dict[str, Any]:
    """The columns known before any request left the box, plus the row's birthday."""
    return {
        "vendor": probe.vendor,
        "is_fallback": probe.is_fallback,
        "provider": _fit(probe.provider, PROBE_NAME_LENGTH),
        "balance_unit": probe.balance_unit,
        "created_at": at,
    }


async def _record_success(
    session: AsyncSession, *, probe: BalanceProbe, divisor: PerSongRate | None, at: datetime
) -> None:
    measured = _measured_values(probe, divisor, at)
    await session.execute(
        upsert_statement(
            session,
            VendorBalanceRow,
            {**_identity(probe, at), **measured},
            index_elements=_CONFLICT_TARGET,
            set_=measured,
        )
    )


async def _record_failure(session: AsyncSession, *, probe: BalanceProbe, at: datetime) -> None:
    """The strict subset. Every column NOT named here keeps the value it already had.

    ``fetched_at`` above all: the row goes on saying "$12.40, measured five hours ago", and
    ``checked_at`` plus ``consecutive_failures`` say how long that has been true. Nulling
    the balance would destroy the number at the exact moment an operator needs it, and would
    make an outage indistinguishable from a deployment that never polled.
    """
    error_code = _fit(probe.error_code, ERROR_CODE_LENGTH)
    insert_only = {
        # Used only when no row exists yet — the "we tried and have never succeeded" state.
        # Every quantity and ``fetched_at`` are left unset, so they are NULL, which
        # satisfies ``ck_vendor_balances_a_measured_balance_carries_its_time`` trivially.
        **_identity(probe, at),
        "checked_at": at,
        "is_last_poll_ok": False,
        "http_status": probe.http_status,
        "error_code": error_code,
        "consecutive_failures": 1,
        "updated_at": at,
    }
    await session.execute(
        upsert_statement(
            session,
            VendorBalanceRow,
            insert_only,
            index_elements=_CONFLICT_TARGET,
            set_={
                "checked_at": at,
                "is_last_poll_ok": False,
                "http_status": probe.http_status,
                "error_code": error_code,
                # A column expression, not a read-modify-write: two workers racing the same
                # window cannot lose a count.
                "consecutive_failures": VendorBalanceRow.consecutive_failures + 1,
                "updated_at": at,
            },
        )
    )


async def record_probe(
    sessions: async_sessionmaker[AsyncSession],
    *,
    probe: BalanceProbe,
    divisor: PerSongRate | None,
    at: datetime,
) -> bool:
    """Persist one probe. ``True`` when the row was written. Never raises.

    ``sessions`` is the factory rather than a session, and the transaction is opened and
    committed here — see the module docstring. ``divisor`` is ignored on a failed probe,
    because an estimate belongs to a balance and a failed probe has none.
    """
    try:
        async with sessions.begin() as session:
            if probe.is_success:
                await _record_success(session, probe=probe, divisor=divisor, at=at)
            else:
                await _record_failure(session, probe=probe, at=at)
    except Exception:
        _LOG.warning(
            "vendor balance row not persisted",
            exc_info=True,
            extra={
                "vendor": probe.vendor.value,
                "is_fallback": probe.is_fallback,
                "probe": probe.provider,
            },
        )
        return False
    return True


async def measure_per_song_rate(
    session: AsyncSession,
    *,
    vendor: Vendor,
    is_fallback: bool,
    window_days: int,
    now: datetime,
    used_units: float | None = None,
    quota_resets_at: datetime | None = None,
) -> PerSongRate | None:
    """What one delivered song has cost at this vendor lately, or ``None``.

    The cohort is ``orders.state = 'delivered' AND orders.created_at >= now - window``.
    ``created_at`` and NOT ``delivered_at``, deliberately: every other window on the
    dashboard is a cohort measure taken on ``created_at`` (``ix_orders_state_created_at`` is
    the index shaped for exactly this predicate), and a divisor windowed differently from the
    charts beside it would reconcile with none of them.

    ``OPENROUTER`` divides measured USD spend by the delivered orders it is attributed to.

    ``ELEVENLABS`` takes a different route entirely — see :func:`_credit_burn_rate` — and
    ``used_units`` and ``quota_resets_at`` are that route's two inputs, read off the probe's
    own reading by the caller. They are keyword-optional because no other vendor has them and
    a probe that answered without them is a real state, not a programming error.

    **Why ElevenLabs is no longer divided by ``billed_characters``.** That is what this
    function used to do, on the ``trailing_tts_characters`` basis, and on this deployment it
    never once produced a number: ``billed_characters`` is written by the TTS leg alone
    (``providers/tts/elevenlabs.py``) and the pipeline's ElevenLabs traffic is
    ``music_compose`` and ``transcription``, neither of which records a character. So the
    divisor was ``NULL`` on every poll, all three estimate columns stayed null together, and
    the meter read "unmeasured · no per-song rate" permanently. A basis that cannot be
    measured on the traffic the system actually sends is not a conservative estimate; it is
    an empty tile with a rationale. The member stays in
    :class:`~bayram.contracts.BalanceEstimateBasis` because rows written under it may still
    exist and must still be readable.

    Every vendor other than those two returns ``None``: there is no measured quantity to
    divide, and inventing one would be worse than an empty tile.
    """
    if vendor is Vendor.ELEVENLABS:
        return await _credit_burn_rate(
            session, used_units=used_units, quota_resets_at=quota_resets_at, now=now
        )
    if vendor is not Vendor.OPENROUTER:
        return None

    cohort = sa.select(OrderRow.id).where(
        OrderRow.state == OrderState.DELIVERED,
        OrderRow.created_at >= now - timedelta(days=window_days),
    )
    quantity: InstrumentedAttribute[Any] = VendorUsageRow.cost_usd
    basis = BalanceEstimateBasis.TRAILING_SPEND_USD
    scope: tuple[sa.ColumnElement[bool], ...] = (VendorUsageRow.is_fallback.is_(is_fallback),)

    row = (
        await session.execute(
            sa.select(
                sa.func.sum(quantity),
                # **Counted over the PRICED rows alone, matching the numerator exactly.**
                # ``SUM`` skips a ``NULL`` cost; a plain ``COUNT(DISTINCT order_id)`` does not
                # skip the order it belonged to. An order whose every OpenRouter call ran on a
                # ``:free`` model — normal here, since the shipped rate card leaves every
                # ``cost_usd`` ``NULL`` — then contributed nothing to the total and a whole
                # song to the divisor, halving the rate and DOUBLING the songs-remaining
                # figure built on it. That is the one direction this estimate must never fail
                # in, and it failed in it silently: the tile reported more cover than the
                # balance can buy, on an account an operator tops up by reading that tile.
                sa.func.count(sa.distinct(VendorUsageRow.order_id)).filter(
                    quantity.is_not(None)
                ),
            ).where(
                VendorUsageRow.vendor == vendor,
                # A fake run measures nothing real, and a demo must not move a divisor that
                # decides whether an operator tops up.
                VendorUsageRow.is_fake.is_(False),
                VendorUsageRow.order_id.in_(cohort),
                *scope,
            )
        )
    ).one()
    total, orders = row[0], row[1]
    # ``NULL`` here is the shipped OpenRouter case, not an error: no row carried a price, so
    # nothing was measured. Zero orders is division by nothing. Both give ``None``, and none
    # of the three estimate columns is written.
    if total is None or not orders:
        return None
    rate = float(total) / float(orders)
    return (rate, basis) if rate > 0.0 else None


#: How long one ElevenLabs quota period runs. The subscription reports when the next reset
#: lands and never when this period opened, so the start is the reset walked back by one
#: period. 30 days and not a calendar month because the reset is an instant on a rolling
#: monthly clock, not the 1st of anything, and a calendar month would move the boundary by up
#: to three days against a reset that does not move at all.
_QUOTA_PERIOD: Final[timedelta] = timedelta(days=30)


async def _credit_burn_rate(
    session: AsyncSession,
    *,
    used_units: float | None,
    quota_resets_at: datetime | None,
    now: datetime,
) -> PerSongRate | None:
    """ElevenLabs credits burned this quota period ÷ songs delivered in it, or ``None``.

    **The numerator is the vendor's number, not ours.** ``balance_used`` is what the
    subscription itself says it has consumed since the last reset, so it counts every leg
    drawing on the credit pool — the music render that writes only ``audio_ms``, the
    transcription that writes nothing priced, a TTS call if one is ever added — without this
    module needing a rate card to convert a duration into a credit. That is the whole reason
    this basis exists: no arithmetic here turns one unit into another, so there is no
    constant to keep current and nothing to be silently wrong about.

    **The denominator is the songs that actually drew on that pool**, not every delivered
    song: delivered orders created in the period that have at least one non-fake ElevenLabs
    call attributed to them. Counting delivered orders outright would put songs ElevenLabs
    never rendered into a divisor against ElevenLabs' own burn, which understates the rate
    and overstates the cover — the direction this metric must never fail in. ``is_fake``
    rows are excluded for the reason they are excluded everywhere: a demo run burns no
    credits and must not move a figure that decides whether an operator tops up.

    **The two halves are windowed to the same period on purpose**, and that is why
    ``window_days`` does not reach this function. ``balance_used`` covers the quota period
    and nothing else; pairing it with a denominator over a shorter operator-chosen window
    would divide a full period's burn by part of a period's songs. The vendor owns this
    window, so the vendor's boundary is the one both halves take.

    **The estimate it yields is a LOWER bound**, stated here and carried to the meter by
    :attr:`~bayram.contracts.BalanceEstimateBasis.QUOTA_PERIOD_CREDIT_BURN`: burn that bought
    no delivered song — a render that failed after billing, a manual experiment in the
    vendor's console — inflates the divisor and shrinks the cover. Erring toward "fewer songs
    than you have" is the safe direction for a number whose only job is to say when to top up.

    ``None`` whenever the division is not defined, which is four separate real states and not
    one error: the account reported no usage figure, it reported no reset instant to walk
    back from, the period start is not yet behind us, or nothing ElevenLabs rendered was
    delivered inside it. Each leaves all three estimate columns null together and the meter
    reading "unmeasured", which is what those states honestly are.

    INDEX: ``ix_orders_state_created_at`` for the cohort, then a nested loop into
    ``ix_vendor_usage_order_id``.
    """
    if used_units is None or used_units <= 0.0 or quota_resets_at is None:
        return None
    period_start = quota_resets_at - _QUOTA_PERIOD
    # A reset more than a period away puts the start in the future, which no cohort can be
    # taken over. It means the vendor moved the plan or the clock is wrong; either way the
    # honest answer is that nothing was measured.
    if period_start >= now:
        return None

    songs = (
        await session.execute(
            sa.select(sa.func.count(sa.distinct(OrderRow.id)))
            .join(VendorUsageRow, VendorUsageRow.order_id == OrderRow.id)
            .where(
                OrderRow.state == OrderState.DELIVERED,
                OrderRow.created_at >= period_start,
                VendorUsageRow.vendor == Vendor.ELEVENLABS,
                VendorUsageRow.is_fake.is_(False),
            )
        )
    ).scalar_one()
    if not songs:
        return None
    rate = float(used_units) / float(songs)
    return (rate, BalanceEstimateBasis.QUOTA_PERIOD_CREDIT_BURN) if rate > 0.0 else None
