"""Delivery: exactly two messages — lyric card image, then the song itself.

Two rules, each of which is a product requirement:
1. When music is generated, send exactly 2 messages (remove all other messages):
   a) Image with lyrics of the song (auto-generated locally via Pillow);
   b) Generated song itself (with audio player, caption, watermark, and post-delivery actions).
2. All other delivery messages (greetings voice notes, text lyric sheets, separate closing messages)
   are removed from the delivery flow.
"""

from __future__ import annotations

from typing import Any
from uuid import uuid4

import pytest
from aiogram import Bot
from aiogram.exceptions import TelegramBadRequest, TelegramForbiddenError
from aiogram.methods import SendMessage, TelegramMethod

from bayram.audio.lyrics_image import LYRICS_IMAGE_FILENAME
from bayram.bot.callbacks import (
    NavAction,
    NavCB,
    SupportAction,
    SupportCB,
    pack_reference,
)
from bayram.bot.delivery import (
    BLOCKED_BY_CUSTOMER_KEY,
    MAX_CAPTION_CHARS,
    DeliveryLedger,
    _fit_caption,
    deliver_kit,
)
from bayram.bot.i18n import escape_html, translate
from bayram.contracts import Err, Kit, Language, Ok
from bayram.watermark import WATERMARK_HANDLE
from tests.conftest import UZBEK_NAME_CANONICAL, make_lyrics
from tests.test_bot.conftest import CHAT_ID, RecordingSession, buttons


async def deliver(bot: Bot, kit: Kit, **overrides: object) -> object:
    return await deliver_kit(bot, chat_id=CHAT_ID, kit=kit, language=Language.EN, **overrides)  # type: ignore[arg-type]


def watermark(key: str, language: Language = Language.EN) -> str:
    """The rendered watermark line, read the way delivery reads it."""
    return translate(key, language, handle=WATERMARK_HANDLE)


def fail_once(session: RecordingSession, method: str, error: Exception) -> None:
    """Arm ``method`` to be rejected exactly once, then let the next attempt through."""
    session.failures[method] = error
    original = session.make_request

    async def once(
        bot: Bot,
        request: TelegramMethod[Any],
        timeout: int | None = None,  # noqa: ASYNC109 - aiogram signature
    ) -> Any:
        try:
            return await original(bot, request, timeout)
        finally:
            session.failures.pop(type(request).__name__, None)

    session.make_request = once  # type: ignore[assignment,method-assign]


async def test_exactly_two_messages_delivered_in_order(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    """Delivery sends exactly two messages: lyric image (SendPhoto) then the song (SendAudio)."""
    # Arrange / Act
    result = await deliver(bot, kit)

    # Assert
    assert isinstance(result, Ok)
    assert len(session.calls) == 2
    assert session.call_names == ("SendPhoto", "SendAudio")
    assert not session.named("SendVoice")
    assert not session.named("SendMessage")


async def test_lyric_image_is_generated_and_sent_as_photo(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    """The lyric image is auto-generated on disk and sent as a photo."""
    # Arrange — ensure no pre-existing image
    image_path = kit.song.path.parent / LYRICS_IMAGE_FILENAME
    if image_path.exists():
        image_path.unlink()

    # Act
    result = await deliver(bot, kit)

    # Assert
    assert isinstance(result, Ok)
    assert image_path.exists()
    assert image_path.stat().st_size > 0
    photo = session.last_named("SendPhoto")
    assert photo is not None


async def test_lyric_image_rendered_with_orange_background_when_google_flow(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    """If music was generated by Google flow, lyrics image background is orange."""
    gemini_song = kit.song.model_copy(update={"provider": "gemini_music"})
    gemini_kit = kit.model_copy(update={"song": gemini_song})
    image_path = gemini_kit.song.path.parent / LYRICS_IMAGE_FILENAME
    if image_path.exists():
        image_path.unlink()

    result = await deliver(bot, gemini_kit)

    assert isinstance(result, Ok)
    assert image_path.exists()
    from PIL import Image

    with Image.open(image_path) as img:
        top_pixel = img.getpixel((0, 0))
        assert top_pixel == (220, 90, 20)


async def test_lyric_image_rendered_with_default_background_when_elevenlabs(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    """If music was generated by ElevenLabs, lyrics image background stays default navy."""
    eleven_song = kit.song.model_copy(update={"provider": "elevenlabs_music"})
    eleven_kit = kit.model_copy(update={"song": eleven_song})
    image_path = eleven_kit.song.path.parent / LYRICS_IMAGE_FILENAME
    if image_path.exists():
        image_path.unlink()

    result = await deliver(bot, eleven_kit)

    assert isinstance(result, Ok)
    assert image_path.exists()
    from PIL import Image

    with Image.open(image_path) as img:
        top_pixel = img.getpixel((0, 0))
        assert top_pixel == (18, 20, 32)


async def test_song_goes_out_as_audio_with_post_delivery_actions(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    """The song goes out with sendAudio, carrying title, caption, watermark, and action buttons."""
    # Arrange / Act
    result = await deliver(bot, kit)

    # Assert
    assert isinstance(result, Ok)
    audio = session.last_named("SendAudio")
    assert audio.title == kit.lyrics.title
    assert UZBEK_NAME_CANONICAL in (audio.caption or "")
    assert watermark("watermark.song") in (audio.caption or "")

    # Post-delivery actions are attached directly to the song message
    payloads = {data for _text, data in buttons(audio.reply_markup)}
    assert NavCB(action=NavAction.MAKE_ANOTHER).pack() in payloads
    assert SupportCB(action=SupportAction.OPEN, ref=pack_reference(kit.order_id)).pack() in payloads


async def test_the_audio_is_never_buried_under_text(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    """No text messages are sent, so audio is never buried under paragraphs."""
    # Arrange / Act
    await deliver(bot, kit)

    # Assert
    assert not session.named("SendMessage")
    assert session.call_names == ("SendPhoto", "SendAudio")


# ---------------------------------------------------------------------------
# Redelivery — the ARQ retry that must not send what already landed
# ---------------------------------------------------------------------------
async def test_a_retry_sends_only_what_did_not_land_the_first_time(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    """If SendAudio fails after SendPhoto landed, retry sends only SendAudio."""
    # Arrange — SendAudio fails
    ledger = DeliveryLedger()
    session.failures["SendAudio"] = TelegramBadRequest(
        method=SendMessage(chat_id=CHAT_ID, text="x"), message="Too Many Requests"
    )
    first = await deliver_kit(bot, chat_id=CHAT_ID, kit=kit, language=Language.EN, ledger=ledger)
    assert isinstance(first, Err)
    assert session.named("SendPhoto")
    assert "song" not in ledger.sent_for(kit.order_id)
    assert "lyric_image" in ledger.sent_for(kit.order_id)

    # Act — the retry, with the outage over
    session.failures.clear()
    session.clear()
    second = await deliver_kit(bot, chat_id=CHAT_ID, kit=kit, language=Language.EN, ledger=ledger)

    # Assert
    assert isinstance(second, Ok)
    assert not session.named("SendPhoto")
    assert session.named("SendAudio")


async def test_a_retry_of_a_delivery_that_fully_landed_sends_nothing(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    # Arrange
    ledger = DeliveryLedger()
    await deliver_kit(bot, chat_id=CHAT_ID, kit=kit, language=Language.EN, ledger=ledger)
    session.clear()

    # Act
    result = await deliver_kit(bot, chat_id=CHAT_ID, kit=kit, language=Language.EN, ledger=ledger)

    # Assert
    assert isinstance(result, Ok)
    assert session.calls == []


async def test_two_orders_do_not_share_delivery_state(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    """The ledger is keyed by order. A second customer's song is not somebody else's."""
    # Arrange
    ledger = DeliveryLedger()
    await deliver_kit(bot, chat_id=CHAT_ID, kit=kit, language=Language.EN, ledger=ledger)
    session.clear()
    other = kit.model_copy(update={"order_id": uuid4()})

    # Act
    await deliver_kit(bot, chat_id=CHAT_ID, kit=other, language=Language.EN, ledger=ledger)

    # Assert
    assert session.named("SendPhoto")
    assert session.named("SendAudio")


async def test_missing_file_is_reported_and_does_not_raise(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    # Arrange
    kit.song.path.unlink()

    # Act
    result = await deliver(bot, kit)

    # Assert
    assert isinstance(result, Err)
    assert "missing-file" in str(result.error.context["failures"])
    assert not session.named("SendAudio")


async def test_a_failed_lyric_image_still_delivers_the_song(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    # Arrange — Photo sending fails
    session.failures["SendPhoto"] = TelegramBadRequest(
        method=SendMessage(chat_id=CHAT_ID, text="x"), message="photo upload error"
    )

    # Act
    result = await deliver(bot, kit)

    # Assert — best effort per asset: lyric image failure does not cost the song
    assert isinstance(result, Err)
    assert session.named("SendAudio")


@pytest.mark.parametrize("language", list(Language))
async def test_captions_are_localised(
    bot: Bot, session: RecordingSession, kit: Kit, language: Language
) -> None:
    # Arrange / Act
    await deliver_kit(bot, chat_id=CHAT_ID, kit=kit, language=language)

    # Assert
    caption = session.last_named("SendAudio").caption
    assert caption
    assert watermark("watermark.song", language) in caption


# ---------------------------------------------------------------------------
# The watermark and branding
# ---------------------------------------------------------------------------
async def test_the_song_goes_out_under_the_bot_as_its_performer(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    """``performer`` is the carrier that survives the file leaving Telegram."""
    # Arrange / Act
    await deliver(bot, kit)

    # Assert
    assert session.last_named("SendAudio").performer == WATERMARK_HANDLE


async def test_a_kit_with_a_cover_sends_it_as_the_audio_thumbnail(
    bot: Bot, session: RecordingSession, kit_with_cover: Kit
) -> None:
    # Arrange / Act
    result = await deliver(bot, kit_with_cover)

    # Assert
    assert isinstance(result, Ok)
    assert session.last_named("SendAudio").thumbnail is not None


async def test_a_kit_without_a_cover_still_delivers_the_song(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    # Arrange / Act
    result = await deliver(bot, kit)

    # Assert
    assert isinstance(result, Ok)
    assert session.last_named("SendAudio").thumbnail is None


async def test_a_cover_whose_file_vanished_still_delivers_the_song(
    bot: Bot, session: RecordingSession, kit_with_cover: Kit
) -> None:
    # Arrange
    cover = kit_with_cover.cover
    assert cover is not None
    cover.path.unlink()

    # Act
    result = await deliver(bot, kit_with_cover)

    # Assert
    assert isinstance(result, Ok)
    assert session.last_named("SendAudio").thumbnail is None


async def test_a_refused_thumbnail_is_retried_once_without_it_rather_than_losing_the_song(
    bot: Bot, session: RecordingSession, kit_with_cover: Kit
) -> None:
    # Arrange — only the FIRST SendAudio is refused
    fail_once(
        session,
        "SendAudio",
        TelegramBadRequest(
            method=SendMessage(chat_id=CHAT_ID, text="x"),
            message="Bad Request: failed to get HTTP URL content",
        ),
    )
    ledger = DeliveryLedger()

    # Act
    result = await deliver(bot, kit_with_cover, ledger=ledger)

    # Assert — a second, stripped attempt, one delivered song, no reported failure
    assert isinstance(result, Ok)
    attempts = session.named("SendAudio")
    assert len(attempts) == 2
    retry = attempts[-1]
    assert retry.performer is None  # type: ignore[attr-defined]
    assert retry.thumbnail is None  # type: ignore[attr-defined]
    assert ledger.sent_for(kit_with_cover.order_id) & {"song"} == {"song"}


async def test_a_song_refused_twice_is_reported_once_and_not_marked_delivered(
    bot: Bot, session: RecordingSession, kit_with_cover: Kit
) -> None:
    # Arrange — every attempt is refused
    ledger = DeliveryLedger()
    session.failures["SendAudio"] = TelegramBadRequest(
        method=SendMessage(chat_id=CHAT_ID, text="x"), message="Bad Request: chat not found"
    )

    # Act
    result = await deliver(bot, kit_with_cover, ledger=ledger)

    # Assert
    assert isinstance(result, Err)
    assert len(session.named("SendAudio")) == 2
    assert "song" not in ledger.sent_for(kit_with_cover.order_id)


async def test_a_blocked_bot_costs_exactly_one_sendaudio_rather_than_two(
    bot: Bot, session: RecordingSession, kit_with_cover: Kit
) -> None:
    # Arrange — every attempt refused with blocked bot
    ledger = DeliveryLedger()
    session.failures["SendAudio"] = TelegramForbiddenError(
        method=SendMessage(chat_id=CHAT_ID, text="x"), message="bot was blocked by the user"
    )

    # Act
    result = await deliver(bot, kit_with_cover, ledger=ledger)

    # Assert — reported once, attempted once, and still not marked delivered
    assert isinstance(result, Err)
    assert len(session.named("SendAudio")) == 1
    assert "song" not in ledger.sent_for(kit_with_cover.order_id)


async def test_a_blocked_customer_is_reported_as_a_structured_fact(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    # Arrange
    session.failures["SendAudio"] = TelegramForbiddenError(
        method=SendMessage(chat_id=CHAT_ID, text="x"),
        message="Forbidden: bot was blocked by the user",
    )

    # Act
    result = await deliver(bot, kit)

    # Assert
    assert isinstance(result, Err)
    assert result.error.context[BLOCKED_BY_CUSTOMER_KEY] is True


async def test_an_ordinary_rejection_is_not_read_as_a_block(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    # Arrange
    session.failures["SendAudio"] = TelegramBadRequest(
        method=SendMessage(chat_id=CHAT_ID, text="x"), message="Bad Request: THUMBNAIL_INVALID"
    )

    # Act
    result = await deliver(bot, kit)

    # Assert
    assert isinstance(result, Err)
    assert result.error.context[BLOCKED_BY_CUSTOMER_KEY] is False


async def test_a_deleted_account_is_not_read_as_a_block(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    # Arrange
    session.failures["SendAudio"] = TelegramForbiddenError(
        method=SendMessage(chat_id=CHAT_ID, text="x"), message="Forbidden: user is deactivated"
    )

    # Act
    result = await deliver(bot, kit)

    # Assert
    assert isinstance(result, Err)
    assert result.error.context[BLOCKED_BY_CUSTOMER_KEY] is False


async def test_a_block_seen_on_photo_is_reported_for_the_whole_delivery(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    # Arrange
    session.failures["SendPhoto"] = TelegramForbiddenError(
        method=SendMessage(chat_id=CHAT_ID, text="x"),
        message="Forbidden: bot was blocked by the user",
    )

    # Act
    result = await deliver(bot, kit)

    # Assert
    assert isinstance(result, Err)
    assert result.error.context[BLOCKED_BY_CUSTOMER_KEY] is True


async def test_the_handle_rides_on_the_audio_caption(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    # Arrange / Act
    await deliver(bot, kit)

    # Assert
    assert watermark("watermark.song") in (session.last_named("SendAudio").caption or "")


async def test_the_longest_title_the_contract_allows_still_fits_the_caption_ceiling(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    # Arrange — title at ceiling
    lyrics = make_lyrics(title="&" * 120)
    heavy = kit.model_copy(update={"lyrics": lyrics})

    # Act
    await deliver(bot, heavy)

    # Assert
    caption = session.last_named("SendAudio").caption
    assert watermark("watermark.song") in caption
    assert escape_html("&" * 120) in caption
    assert len(caption) <= MAX_CAPTION_CHARS


def test_a_caption_over_the_ceiling_is_clipped_at_a_line_boundary() -> None:
    # Arrange
    heading = "🎵 <b>A Song</b>"
    overflowing = "t" * MAX_CAPTION_CHARS

    # Act
    fitted = _fit_caption(f"{heading}\n{overflowing}")

    # Assert
    assert fitted == heading


def test_a_caption_with_no_line_that_fits_keeps_the_watermark_it_was_composed_for() -> None:
    # Arrange
    mark = watermark("watermark.song")

    # Act
    fitted = _fit_caption("🎵 <b>{}</b>\n\n{}".format("t" * MAX_CAPTION_CHARS, mark))

    # Assert
    assert fitted == mark
    assert "<b>" not in fitted


def test_a_caption_inside_the_ceiling_is_handed_back_untouched() -> None:
    # Arrange
    caption = f"🎵 <b>A Song</b>\nSound on.\n\n{watermark('watermark.song')}"

    # Act / Assert
    assert _fit_caption(caption) == caption


async def test_the_watermark_is_localised_with_the_rest_of_the_delivery(
    bot: Bot, session: RecordingSession, kit: Kit
) -> None:
    # Arrange / Act
    await deliver_kit(bot, chat_id=CHAT_ID, kit=kit, language=Language.RU)

    # Assert
    caption = session.last_named("SendAudio").caption
    assert watermark("watermark.song", Language.RU) in caption
    assert watermark("watermark.song", Language.EN) not in caption
