"""The ``vendor_balances`` WRITER, and the trailing measurement behind "songs remaining".

Beside :mod:`hbd.db.vendor_usage` rather than under ``hbd.db.admin``, and the placement is
structural rather than tidy. ``hbd.db.admin`` is the admin panel's persistence and nothing
there commits, because the caller owns the transaction. This module is neither: it runs in
the ARQ worker and owns its transaction outright, exactly like ``DbUsageSink``, whose
reasoning applies verbatim — joining whatever transaction the caller happens to be in would
let an unrelated rollback erase the record of a probe that really happened. Keeping it out
of ``hbd.db.admin`` is also the second, structural expression of the security boundary: the
admin package holds no module that can WRITE this table, and no module that can reach a
vendor.

**THE COLUMN-SELECTIVE FAILURE UPSERT IS THE POINT OF THIS MODULE.** There are two
statements, not one, because the failure path must name a STRICT SUBSET of the columns —
everything it does NOT name is what survives a vendor outage. One statement passing ``None``
for the unmeasured quantities would blank the last known balance on the first 500, which is
the exact opposite of what the tile is for: an operator wants the last known figure most at
the moment the vendor is down. The set-difference between the two update mappings IS the
design, so both are spelled out by hand and neither is generated by filtering a dict, where
a later refactor could quietly widen one.

``consecutive_failures`` increments as a COLUMN EXPRESSION inside the ``DO UPDATE`` clause,
which both dialects support, so two workers racing the same window cannot lose a count to a
read-modify-write.

**IT NEVER RAISES**, for ``DbUsageSink``'s stated reason: instrumentation that stops working
looks exactly like a deployment with no traffic. A failed write is logged with the vendor
and the error, and the caller continues to the next probe.

**THE DIVISOR IS MEASURED, NOT CONFIGURED, and that is a correction worth recording.**
``music_usd_per_minute`` and ``elevenlabs_usd_per_character`` are NOT a per-song rate; they
are one layer upstream — the rates that make ``vendor_usage.cost_usd`` non-``NULL`` at all.
Turning them into a per-song figure would need an assumed song shape (how many characters is
a greeting, how many tokens is a lyric, how many seconds is a render), none of which is a
setting and all of which would be invented — fabricating precisely the number
``vendor_balances`` exists not to fabricate. :func:`measure_per_song_rate` divides what was
actually spent by the orders it was actually spent on, and returns ``None`` rather than a
zero whenever it cannot. The consequence is honest and visible: with the shipped rate card
(all four ``HBD_LLM_*_USD_PER_MILLION_*`` at 0.0) every OpenRouter ``cost_usd`` is ``NULL``,
the divisor is ``None``, all three estimate columns stay ``NULL`` together under
``ck_vendor_balances_estimate_carries_its_basis``, and the tile reads "needs balances".
"""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import TYPE_CHECKING, Any, Final

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker
from sqlalchemy.orm import InstrumentedAttribute

from hbd.contracts import BalanceEstimateBasis, OrderState, Vendor
from hbd.db.credit_sql import upsert_statement
from hbd.db.models.order import OrderRow
from hbd.db.models.vendor_balance import (
    ERROR_CODE_LENGTH,
    PLAN_TIER_LENGTH,
    PROBE_NAME_LENGTH,
    RESET_HINT_LENGTH,
    STATUS_LENGTH,
    VendorBalanceRow,
)
from hbd.db.models.vendor_usage import VendorUsageRow
from hbd.logging import get_logger

if TYPE_CHECKING:  # pragma: no cover - a typing-only edge, see the note below
    # Imported for the annotation and NOT at runtime, on purpose. ``hbd.db`` is the lower
    # layer and ``hbd.runtime`` is the higher one; a runtime import here would invert that
    # for the sake of a type name. The writer only ever reads attributes off the probe, so
    # the annotation is all it needs.
    from hbd.runtime.vendor_balance_probes import BalanceProbe

__all__ = ["record_probe", "measure_per_song_rate", "PerSongRate"]

_LOG = get_logger(__name__)

#: The two columns the primary key is made of, and therefore the ``ON CONFLICT`` target.
#: One row per billing account, so a duplicate is impossible rather than merely unusual.
_CONFLICT_TARGET: Final[tuple[str, ...]] = ("vendor", "is_fallback")

#: ``(rate, basis)``. The two always travel together, because a divisor whose provenance is
#: unknown cannot be trusted differently from one whose provenance is known — which is the
#: whole argument for :class:`hbd.contracts.BalanceEstimateBasis`.
type PerSongRate = tuple[float, BalanceEstimateBasis]


def _fit(value: str | None, limit: int) -> str | None:
    """Trim a vendor's own word to the column that holds it.

    Done HERE and not in the probe because this is the layer allowed to import the model
    that owns those widths. A vendor is free to lengthen its tier vocabulary, and a
    ``StringDataRightTruncation`` on Postgres would lose a whole probe over a cosmetic
    field.
    """
    return value[:limit] if value is not None else None


def _songs_remaining(balance_remaining: float | None, rate: float) -> int | None:
    """FLOOR, never round.

    A rounded-up "1 song remaining" on a balance that cannot pay for one is precisely the
    failure this tile exists to prevent, and ``//`` on a positive divisor is the whole
    guard.
    """
    if balance_remaining is None or rate <= 0.0:
        return None
    return int(balance_remaining // rate)


def _measured_values(
    probe: BalanceProbe, divisor: PerSongRate | None, at: datetime
) -> dict[str, Any]:
    """Everything a SUCCESSFUL probe writes, quantities included."""
    reading = probe.reading
    assert reading is not None, "a successful probe carries a reading by construction"
    rate = divisor[0] if divisor is not None else None
    songs = _songs_remaining(reading.balance_remaining, rate) if rate is not None else None
    # All three estimate columns move together or none of them do — the database refuses any
    # other combination, and building them in one place is what keeps that a fact rather
    # than a promise three call sites keep.
    has_estimate = songs is not None and rate is not None and divisor is not None
    return {
        "balance_remaining": reading.balance_remaining,
        "balance_total": reading.balance_total,
        "balance_used": reading.balance_used,
        "is_unbounded": reading.is_unbounded,
        "quota_resets_at": reading.quota_resets_at,
        "quota_reset_hint": _fit(reading.quota_reset_hint, RESET_HINT_LENGTH),
        "plan_tier": _fit(reading.plan_tier, PLAN_TIER_LENGTH),
        "subscription_status": _fit(reading.subscription_status, STATUS_LENGTH),
        "songs_remaining": songs if has_estimate else None,
        "per_song_rate": rate if has_estimate else None,
        "estimate_basis": divisor[1] if has_estimate and divisor is not None else None,
        "fetched_at": at,
        "checked_at": at,
        "is_last_poll_ok": True,
        "http_status": probe.http_status,
        "error_code": None,
        "consecutive_failures": 0,
        "updated_at": at,
    }


def _identity(probe: BalanceProbe, at: datetime) -> dict[str, Any]:
    """The columns known before any request left the box, plus the row's birthday."""
    return {
        "vendor": probe.vendor,
        "is_fallback": probe.is_fallback,
        "provider": _fit(probe.provider, PROBE_NAME_LENGTH),
        "balance_unit": probe.balance_unit,
        "created_at": at,
    }


async def _record_success(
    session: AsyncSession, *, probe: BalanceProbe, divisor: PerSongRate | None, at: datetime
) -> None:
    measured = _measured_values(probe, divisor, at)
    await session.execute(
        upsert_statement(
            session,
            VendorBalanceRow,
            {**_identity(probe, at), **measured},
            index_elements=_CONFLICT_TARGET,
            set_=measured,
        )
    )


async def _record_failure(session: AsyncSession, *, probe: BalanceProbe, at: datetime) -> None:
    """The strict subset. Every column NOT named here keeps the value it already had.

    ``fetched_at`` above all: the row goes on saying "$12.40, measured five hours ago", and
    ``checked_at`` plus ``consecutive_failures`` say how long that has been true. Nulling
    the balance would destroy the number at the exact moment an operator needs it, and would
    make an outage indistinguishable from a deployment that never polled.
    """
    error_code = _fit(probe.error_code, ERROR_CODE_LENGTH)
    insert_only = {
        # Used only when no row exists yet — the "we tried and have never succeeded" state.
        # Every quantity and ``fetched_at`` are left unset, so they are NULL, which
        # satisfies ``ck_vendor_balances_a_measured_balance_carries_its_time`` trivially.
        **_identity(probe, at),
        "checked_at": at,
        "is_last_poll_ok": False,
        "http_status": probe.http_status,
        "error_code": error_code,
        "consecutive_failures": 1,
        "updated_at": at,
    }
    await session.execute(
        upsert_statement(
            session,
            VendorBalanceRow,
            insert_only,
            index_elements=_CONFLICT_TARGET,
            set_={
                "checked_at": at,
                "is_last_poll_ok": False,
                "http_status": probe.http_status,
                "error_code": error_code,
                # A column expression, not a read-modify-write: two workers racing the same
                # window cannot lose a count.
                "consecutive_failures": VendorBalanceRow.consecutive_failures + 1,
                "updated_at": at,
            },
        )
    )


async def record_probe(
    sessions: async_sessionmaker[AsyncSession],
    *,
    probe: BalanceProbe,
    divisor: PerSongRate | None,
    at: datetime,
) -> bool:
    """Persist one probe. ``True`` when the row was written. Never raises.

    ``sessions`` is the factory rather than a session, and the transaction is opened and
    committed here — see the module docstring. ``divisor`` is ignored on a failed probe,
    because an estimate belongs to a balance and a failed probe has none.
    """
    try:
        async with sessions.begin() as session:
            if probe.is_success:
                await _record_success(session, probe=probe, divisor=divisor, at=at)
            else:
                await _record_failure(session, probe=probe, at=at)
    except Exception:
        _LOG.warning(
            "vendor balance row not persisted",
            exc_info=True,
            extra={
                "vendor": probe.vendor.value,
                "is_fallback": probe.is_fallback,
                "probe": probe.provider,
            },
        )
        return False
    return True


async def measure_per_song_rate(
    session: AsyncSession,
    *,
    vendor: Vendor,
    is_fallback: bool,
    window_days: int,
    now: datetime,
) -> PerSongRate | None:
    """What one delivered song has cost at this vendor lately, or ``None``.

    The cohort is ``orders.state = 'delivered' AND orders.created_at >= now - window``.
    ``created_at`` and NOT ``delivered_at``, deliberately: every other window on the
    dashboard is a cohort measure taken on ``created_at`` (``ix_orders_state_created_at`` is
    the index shaped for exactly this predicate), and a divisor windowed differently from the
    charts beside it would reconcile with none of them.

    ``OPENROUTER`` divides measured USD spend by the delivered orders it is attributed to.
    ``ELEVENLABS`` divides billed TTS characters the same way — and the basis it returns says
    ``trailing_tts_characters`` out loud, because the music leg draws on the SAME ElevenLabs
    credit pool while recording ``audio_ms`` rather than ``billed_characters``. That divisor
    therefore undercounts, and the songs-remaining figure built on it is an UPPER BOUND: it
    promises more songs than the account can pay for, which is the one direction of error
    this metric must never make silently. The enum member is how the schema carries the
    warning; a tile that renders the number without it is rendering a guess as a fact.

    Every vendor other than those two returns ``None``: there is no measured quantity to
    divide, and inventing one would be worse than an empty tile.
    """
    cohort = sa.select(OrderRow.id).where(
        OrderRow.state == OrderState.DELIVERED,
        OrderRow.created_at >= now - timedelta(days=window_days),
    )
    if vendor is Vendor.OPENROUTER:
        quantity: InstrumentedAttribute[Any] = VendorUsageRow.cost_usd
        basis = BalanceEstimateBasis.TRAILING_SPEND_USD
        scope: tuple[sa.ColumnElement[bool], ...] = (VendorUsageRow.is_fallback.is_(is_fallback),)
    elif vendor is Vendor.ELEVENLABS:
        quantity = VendorUsageRow.billed_characters
        basis = BalanceEstimateBasis.TRAILING_TTS_CHARACTERS
        scope = ()
    else:
        return None

    row = (
        await session.execute(
            sa.select(
                sa.func.sum(quantity),
                sa.func.count(sa.distinct(VendorUsageRow.order_id)),
            ).where(
                VendorUsageRow.vendor == vendor,
                # A fake run measures nothing real, and a demo must not move a divisor that
                # decides whether an operator tops up.
                VendorUsageRow.is_fake.is_(False),
                VendorUsageRow.order_id.in_(cohort),
                *scope,
            )
        )
    ).one()
    total, orders = row[0], row[1]
    # ``NULL`` here is the shipped OpenRouter case, not an error: no row carried a price, so
    # nothing was measured. Zero orders is division by nothing. Both give ``None``, and none
    # of the three estimate columns is written.
    if total is None or not orders:
        return None
    rate = float(total) / float(orders)
    return (rate, basis) if rate > 0.0 else None
