"""The watermark vocabulary: the handle, the two sentences, and the strings that carry them.

**The single invariant: nothing in this module ever touches a ``LyricDraft``.** Every value
here is added to RENDERED output only — the cover image, the ID3 tags, the Telegram caption
and the archived lyric sheet — and never to the text that is handed to the music vendor. A
watermark that reaches the vendor payload is not a watermark, it is a lyric: the model will
set it to music and the customer will hear a voice singing "generated by at bayram_uzbot" in the
middle of their birthday song. That is the defect this module's shape exists to prevent, and
:func:`contains_watermark` exists so the packages that build the vendor payload can assert
the absence in a test rather than trust a review.

**This module is a HARD LEAF: stdlib only, with no first-party imports at all — not even
``bayram.errors``.** Four very differently-shaped things import it: the bot process (captions),
the delivery layer (the lyric sheet), the pipeline (the cover image) and the ffmpeg argv
builders (the metadata tags). Those already sit on opposite sides of every layering rule
this codebase has, so the only import edge that can never create a cycle is no edge at all.
There is deliberately nothing here to import anyway — it is four constants and two pure
functions.

The strings are ASCII on purpose. :func:`audio_tags` produces ``ffmpeg -metadata key=value``
argv elements, and the moment a value can carry a newline, an ``=`` or a non-ASCII byte,
"what does the shell do with this" becomes a question somebody has to answer correctly under
pressure. Refusing to represent those characters at all is cheaper than answering it.
"""

from __future__ import annotations

from typing import Final

__all__ = [
    "WATERMARK_HANDLE",
    "WATERMARK_SONG_TAG",
    "WATERMARK_INVITE_TAG",
    "SHEET_RULE",
    "COVER_LINES",
    "audio_tags",
    "contains_watermark",
]

#: Which bot this is. A module constant and deliberately **not** a ``Settings`` field.
#: ``bayram.bot.delivery.deliver_kit`` is not handed ``Settings`` and neither is
#: ``bayram.runtime.jobs``, so making the handle configurable means threading ``Settings``
#: through the whole delivery signature for a value that is a fact about the deployment's
#: own identity rather than a knob anybody tunes. It is also how the four carriers come to
#: disagree: a configurable handle is a handle the cover image renders from one source, the
#: ID3 tags from another and the caption from a third, and nothing notices until a customer
#: forwards a song whose picture and whose caption advertise two different bots.
WATERMARK_HANDLE: Final[str] = "@bayram_uzbot"

#: What the recording says about itself — the ID3 comment and the audio caption line. Says
#: "generated", not "made", because the honest claim is the one that survives a listener
#: asking whether a person wrote it.
WATERMARK_SONG_TAG: Final[str] = f"This song has been generated by {WATERMARK_HANDLE}"

#: The half that is marketing rather than provenance: what a person who was FORWARDED the
#: song needs in order to buy their own. Separate from the tag above because the two land in
#: different places — provenance goes on the file, the invitation goes on the message.
WATERMARK_INVITE_TAG: Final[str] = f"Generate yours at {WATERMARK_HANDLE}"

#: The header and footer of the archived ``lyrics.txt``. A rule rather than a bare sentence
#: because that artefact is a plain text file with NO language attached — it is generated,
#: never translated, and is read outside Telegram where no caption travels with it — so the
#: only thing available to say "this line is not part of the song" is punctuation.
SHEET_RULE: Final[str] = f"--- {WATERMARK_INVITE_TAG} ---"

#: What the generated cover art prints, one element per line. Split here rather than wrapped
#: at draw time because the image is 320x320 and the line breaks are a layout decision that
#: has to be legible as a Telegram thumbnail — roughly nine characters wide — not whatever a
#: greedy wrapper happens to produce.
COVER_LINES: Final[tuple[str, ...]] = ("GENERATE", "YOURS AT", WATERMARK_HANDLE)

#: The two characters an ``ffmpeg -metadata`` value may not contain. ``=`` because it is the
#: separator itself, so a value carrying one silently truncates the tag; ``\n`` because a
#: newline in an argv element is unrepresentable in every log line and shell transcript that
#: will ever be used to debug the mux.
_FORBIDDEN_IN_TAG_VALUES: Final[tuple[str, ...]] = ("\n", "\r", "=")

#: Lower-cased needles :func:`contains_watermark` looks for. The prose fragment is here as
#: well as the handle because a caption may be reworded in a locale catalogue without the
#: handle changing, and a test that only knew the handle would keep passing while the actual
#: sentence leaked into a vendor payload.
_WATERMARK_NEEDLES: Final[tuple[str, ...]] = (WATERMARK_HANDLE.lower(), "generated by")


def audio_tags(*, title: str) -> tuple[tuple[str, str], ...]:
    """The four ID3 tags a watermarked render carries, as ordered ``(key, value)`` pairs.

    Returned as a tuple of pairs rather than a mapping because the caller turns each one
    into two argv elements — ``-metadata`` then ``key=value`` — and argv is ordered. A dict
    would work today and would leave the ordering to whatever insertion order the next edit
    happens to produce, which is exactly the kind of thing that makes a diff of an ffmpeg
    command unreadable.

    ``title`` is the only value that varies, and it is the only one that is NOT a watermark:
    it is the song's own name, so a phone's lock screen shows the customer's song rather
    than an advertisement. The other three are fixed — artist, album and comment together
    mean that whichever field a given player chooses to surface, the handle is in it.

    Every value is sanitised, not validated: a title arrives from a locale catalogue or a
    recipient's name and refusing to render at all because it contained an ``=`` would cost
    the customer their song over a cosmetic tag. Stripping is the degradation that keeps the
    mux total.
    """
    return (
        ("title", _sanitise_tag_value(title)),
        ("artist", _sanitise_tag_value(WATERMARK_HANDLE)),
        ("album", _sanitise_tag_value(WATERMARK_INVITE_TAG)),
        ("comment", _sanitise_tag_value(WATERMARK_SONG_TAG)),
    )


def _sanitise_tag_value(value: str) -> str:
    """Make ``value`` safe to place after ``-metadata key=``.

    Two passes, in this order and not the other one. First the structural characters go,
    because an ``=`` or a newline changes what ffmpeg parses rather than merely how it looks.
    Then everything outside ASCII goes, because the tag is written into an ID3 frame whose
    encoding is negotiated by the muxer and a non-ASCII byte turns a cosmetic tag into an
    encoding question nobody wants to own. Collapsing the leftover whitespace last keeps a
    stripped character from leaving a double space behind.
    """
    cleaned = value
    for forbidden in _FORBIDDEN_IN_TAG_VALUES:
        cleaned = cleaned.replace(forbidden, " ")
    cleaned = cleaned.encode("ascii", "ignore").decode("ascii")
    return " ".join(cleaned.split())


def contains_watermark(text: str) -> bool:
    """True when ``text`` carries any part of the watermark, case-insensitively.

    **This exists for other packages' tests, not for production code.** The invariant at the
    top of this module — the watermark never enters a ``LyricDraft`` or the payload posted to
    the music vendor — is the kind of thing that holds until someone adds one convenient
    ``caption + "\\n" + lyric`` and nothing goes red. A predicate makes it assertable: the
    lyric-writing and vendor-submission packages each pin ``not contains_watermark(payload)``,
    so the leak fails a test instead of shipping a song that sings its own advertisement.

    Deliberately generous rather than exact. It matches the prose fragment as well as the
    handle, so a reworded caption that still says "generated by" is still caught; a false
    positive costs a test author one rename, while a false negative costs a customer a
    ruined song.
    """
    haystack = text.lower()
    return any(needle in haystack for needle in _WATERMARK_NEEDLES)
